# 3 . Desarrollo de nuevos operadores

Consideramos el espacio desarrollado por la base ortonormal {$|n⟩$}${}_{n=0,1,2,3,4}$. El operador $\hat{a}$ actúa sobre los elementos de la base como $\hat{a}|n⟩ = \sqrt{n}|n − 1⟩$ y el operador $\hat{a}^{\dagger}$ lo hace como $\hat{a}^{\dagger}|n⟩ = \sqrt{n + 1}|n + 1⟩$. Muestre la representación matricial de los operadores $\hat{a}$ y $\hat{a}^{\dagger}$ en esta base. Calcule también la matriz del operador $\hat{N}$ = $\hat{a}^{\dagger}\hat{a}$. Desarrolle estos operadores en la base {$|n⟩$} y compruebe cómo actúan sobre los vectores de la base.



In [46]:
#Importamos las librerias y funciones que podamos usar sobre la marcha
import math
import numpy as np

## Definicion de funciones a usar

In [47]:
def dcroc(i, j):
    if i == j:
        return 1
    else:
        return 0


def baseRn(dim):
    base = []
    for i in range(1, dim + 1):
        base.append([dcroc(j, i) for j in range(1, dim + 1)])
    return np.array(base)


**Definimos una base de R5 ortogonal**

In [48]:
baseR5 = baseRn(5)

print(baseR5)

u0 = np.array([baseR5[0]]).T
u1 = np.array([baseR5[1]]).T
u2 = np.array([baseR5[2]]).T
u3 = np.array([baseR5[3]]).T
u4 = np.array([baseR5[4]]).T

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


__Definimos el operador a desde su definicion en el ejecicio. Similar para a daga__

In [49]:
a = np.round(u0@u1.T + math.sqrt(2)*u1@u2.T + math.sqrt(3)*u2@u3.T + math.sqrt(4)*u3@u4.T,3)

print(f"a = \n{a}\n\n||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\n")

adag = np.round(u1@u0.T + math.sqrt(2)*u2@u1.T + math.sqrt(3)*u3@u2.T + math.sqrt(4)*u4@u3.T,3)

print(f"adag = \n{adag}")


a = 
[[0.    1.    0.    0.    0.   ]
 [0.    0.    1.414 0.    0.   ]
 [0.    0.    0.    1.732 0.   ]
 [0.    0.    0.    0.    2.   ]
 [0.    0.    0.    0.    0.   ]]

||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

adag = 
[[0.    0.    0.    0.    0.   ]
 [1.    0.    0.    0.    0.   ]
 [0.    1.414 0.    0.    0.   ]
 [0.    0.    1.732 0.    0.   ]
 [0.    0.    0.    2.    0.   ]]


__Por último definimos N como la multiplicacion de adag*a__

In [50]:
N = np.round(adag@a,2)

print(f"N = \n{N}")

N = 
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]


Aplicamos estos operadores sobre cada uno de los vectores de la base y observamos los resultados.

In [51]:
print (f"a*{u0.T} = {(a@u0).T}")
print (f"a*{u1.T} = {math.sqrt(1)}*{(a@u1/math.sqrt(1)).T}")
print (f"a*{u2.T} = {round(math.sqrt(2),3)}*{(a@u2/round(math.sqrt(2),3)).T}")
print (f"a*{u3.T} = {round(math.sqrt(3),3)}*{(a@u3/round(math.sqrt(3),3)).T}")
print (f"a*{u4.T} = {round(math.sqrt(4),3)}*{(a@u4/round(math.sqrt(4),3)).T}")

a*[[1 0 0 0 0]] = [[0. 0. 0. 0. 0.]]
a*[[0 1 0 0 0]] = 1.0*[[1. 0. 0. 0. 0.]]
a*[[0 0 1 0 0]] = 1.414*[[0. 1. 0. 0. 0.]]
a*[[0 0 0 1 0]] = 1.732*[[0. 0. 1. 0. 0.]]
a*[[0 0 0 0 1]] = 2.0*[[0. 0. 0. 1. 0.]]


In [52]:
print (f"adag*{u0.T} = {(adag@u0).T}")
print (f"adag*{u1.T} = {round(math.sqrt(1+1),3)}*{(adag@u1/round(math.sqrt(1+1),3)).T}")
print (f"adag*{u2.T} = {round(math.sqrt(2+1),3)}*{(adag@u2/round(math.sqrt(2+1),3)).T}")
print (f"adag*{u3.T} = {round(math.sqrt(3+1),3)}*{(adag@u3/round(math.sqrt(3+1),3)).T}")
print (f"adag*{u4.T} = {round(math.sqrt(4+1),3)}*{(adag@u4/round(math.sqrt(4+1),3)).T}")

adag*[[1 0 0 0 0]] = [[0. 1. 0. 0. 0.]]
adag*[[0 1 0 0 0]] = 1.414*[[0. 0. 1. 0. 0.]]
adag*[[0 0 1 0 0]] = 1.732*[[0. 0. 0. 1. 0.]]
adag*[[0 0 0 1 0]] = 2.0*[[0. 0. 0. 0. 1.]]
adag*[[0 0 0 0 1]] = 2.236*[[0. 0. 0. 0. 0.]]


In [53]:
print (f"N*{u0.T} = {(N@u0).T}")
print (f"N*{u1.T} = {(N@u1).T}")
print (f"N*{u2.T} = {(N@u2).T}")
print (f"N*{u3.T} = {(N@u3).T}")
print (f"N*{u4.T} = {(N@u4).T}")

N*[[1 0 0 0 0]] = [[0. 0. 0. 0. 0.]]
N*[[0 1 0 0 0]] = [[0. 1. 0. 0. 0.]]
N*[[0 0 1 0 0]] = [[0. 0. 2. 0. 0.]]
N*[[0 0 0 1 0]] = [[0. 0. 0. 3. 0.]]
N*[[0 0 0 0 1]] = [[0. 0. 0. 0. 4.]]
