# 1 . Desarrollo en bases bidimensionales

Sean los operadores $\hat{A}$ y $\hat{B}$ definidos en el espacio desarrollado por los vectores {$|u_{1}⟩, |u_{2}⟩$} como:

$\hat{A} = −|u_{1}⟩⟨u_{2}| − |u_{2}⟩⟨u_{1}|$

y

$\hat{B} = 3|u_{1}⟩⟨u_{1}| + 3|u_{2}⟩⟨u_{2}| − |u_{1}⟩⟨u_{2}| − |u_{2}⟩⟨u_{1}|$

Compruebe si los operadores conmutan aplicando el conmutador $[\hat{A}, \hat{B}]$ sobre una función cualquiera
$|Ψ⟩ = C_{1}|u_{1}⟩ + C_{2}|u_{2}⟩$. Encuentre los autovalores del operador $\hat{B}$, {$|ψ_{1}⟩, |ψ_{2}⟩$}, y compruebe que
{$\hat{A}|ψ1⟩, \hat{A}|ψ2⟩$} son también autovectores de $\hat{B}$. ¿Por qué deberían ser los autovectores de $\hat{A}$ también
autovectores de $\hat{B}$? Compruébelo.

Para trabajar usando Python el punto 1, como la base bidimensional no esta definida,
se tratara la base como si fueran los vectores  de R2, osea e1 y e2, por lo que el Ket
estará asociado  con el vector columna y el bra estara asociado al vector fila.

In [1]:
#Importamos las librerias que se van a usar.

from sympy.core.random import random
import numpy as np

### DEFINICIÓN DE FUNCIONES

In [2]:
#Definimos la funcion delta de croniquer
def dcroc(i, j):
    if i == j:
        return 1
    else:
        return 0

#Definimos la función Que genera una base ortogonal en Rn
def baseRn(dim):
    base = []
    for i in range(1, dim + 1):
        base.append([dcroc(j, i) for j in range(1, dim + 1)])
    return np.array(base)

 Creadas las funciones, solo basta crear los elementos con los que se va a trabajar

In [3]:
dim = 2 # Dimension de la base, R2
base = baseRn(dim) # Con esta funcion obtenemos una base del plano que va a representar a nuestra base
                      #  de funciones.

# Teniendo la base podemos definir u1 y u2

u1 = np.array([base[0]]).T
u2 = np.array([base[1]]).T

print (f"u1 = \n{u1}\n||||||\nu2 = \n{u2} ")

u1 = 
[[1]
 [0]]
||||||
u2 = 
[[0]
 [1]] 


Definimos los operadores desde lo que nos da el ejercicio

In [4]:
# Definimos el operador A y B

A = -u1 @ u2.T -u2 @ u1.T # Teniendo en cuenta que la representacion de los KET son columna y los BRA son vectores
                          # fila.

B = 3*u1 @ u1.T +3*u2 @ u2.T -u1 @ u2.T -u2 @ u1.T

print (f"A = \n {A}\n|||||||\nB = \n {B}")

A = 
 [[ 0 -1]
 [-1  0]]
|||||||
B = 
 [[ 3 -1]
 [-1  3]]


Analizamos si si conmutan

In [5]:
Phi = random()*u1 -random()*u2 #Generamos una combinacion lineal aleatoria para generalidad
conmut =(A@B)-(B@A)

print (f"Phi = \n{Phi}\n|||||")
print(f"[A,B]*phi = {(conmut@Phi).sum()}")

Phi = 
[[ 0.67977778]
 [-0.10055305]]
|||||
[A,B]*phi = 0.0


Buscamos los autoestados del operador B diagonalizando la matriz de B

In [6]:
eigvals1, eigvec1 = np.linalg.eig(B)

#Veamos que en efecto se cumple que hayamos los autovectores con sus autovalores

b1 = eigvals1[0]
b2 = eigvals1[1]

phiB1 = (eigvec1.T)[0].T
phiB2 = (eigvec1.T)[1].T

print (f"lambdaB1 = {b1}")
print (f"lambdaB2 = {b2}\n\n")

print (f"phiB1 = {phiB1}\nB*phiB1/lambdaB1 = {(B@phiB1)/b1} --->    Comparacion entre phiB1 y B*phiB1/lambdaB1")
print("\n\n|||||||||||||||||||||||||||||||\n\n")
print (f"phiB2 = {phiB2}\nB*phiB2/lambdaB2 = {(B@phiB2)/b2} --->   Comparacion entre phiB2 y B*phiB2/lambdaB2")


lambdaB1 = 4.0
lambdaB2 = 2.0


phiB1 = [ 0.70710678 -0.70710678]
B*phiB1/lambdaB1 = [ 0.70710678 -0.70710678] --->    Comparacion entre phiB1 y B*phiB1/lambdaB1


|||||||||||||||||||||||||||||||


phiB2 = [0.70710678 0.70710678]
B*phiB2/lambdaB2 = [0.70710678 0.70710678] --->   Comparacion entre phiB2 y B*phiB2/lambdaB2


Si $A*phiB1$ y $A*phiB2$ son tambien autovectores de $B$ significa que $phiB1$ y $phiB2$ son autoestados de $A$.

Por lo que hacemos el mismo procedimiento para $A$:

In [7]:
eigvals2, eigvec2 = np.linalg.eig(A)

a1 = eigvals2[0]
a2 = eigvals2[1]

Sin usar los autovectores que me entregan para $A$, usando solo los de $B$, veamos si nos da iguales a los autovectores de $B$

In [8]:
print (f"lambdaA1 = {a1}")
print (f"lambdaA2 = {a2}\n\n")

print (f"phiB1 = {phiB1}\nA*phiB1/lambdaA1 = {(A@phiB1)/a1}  --->  Comparacion entre phiB1 y A*phiB1/lambdaA1")
print("\n\n|||||||||||||||||||||||||||||||\n\n")
print (f"phiB2 = {phiB2}\nA*phiB2/lambdaA2 = {(A@phiB2)/a2}  --->  Comparacion entre phiB2 y A*phiB2/lambdaA2")


lambdaA1 = 1.0
lambdaA2 = -1.0


phiB1 = [ 0.70710678 -0.70710678]
A*phiB1/lambdaA1 = [ 0.70710678 -0.70710678]  --->  Comparacion entre phiB1 y A*phiB1/lambdaA1


|||||||||||||||||||||||||||||||


phiB2 = [0.70710678 0.70710678]
A*phiB2/lambdaA2 = [0.70710678 0.70710678]  --->  Comparacion entre phiB2 y A*phiB2/lambdaA2


Vemos que en efecto obtenemos los mismos autovectores de $B$ usando los obtenidos para $B$ suponiendo que son
los mismos autovectores en $A$, esto es debido a que tanto el operador $A$ como $B$ son matrices hermíticas y ademas conmutan, por lo que comparten un conjunto comun de autovalores debido a que no hay degeneracion en sus autovalores.