# 4 . Rotaciones como diagonalizadores

Consideremos una rotación en el espacio desarrollado por {$|u1⟩, |u2⟩$} definida como:

$|ψ1⟩ = cos(θ)|u1⟩ + sin(θ)|u2⟩$

$|ψ2⟩ = − sin(θ)|u1⟩ + cos(θ)|u2⟩$

Encuentre la matriz de la transformación $U$ y su hermítica conjugada $U^{\dagger}$. Considere una matriz real que representa un operador hermítico $\hat{A}$ en ese espacio. Encuentre la matriz del operador en el espacio rotado y encuentre el  ́angulo $\theta_{0}$ que diagonaliza la matriz. Encuentre el ángulo de rotación que diagonaliza la matriz $\begin{pmatrix}
a & a \\
a & -a \\
\end{pmatrix}$ donde $a$ es un número real. Use esta rotación para calcular los autovalores del operador y sus autovectores en la base original.

In [73]:
#Como siempre lo primero sera traer las librerias que vamos a usar
import math
from sympy.core.random import random
import numpy as np

## Definicion de funciones a usar

De nuevo usaremos como en el ejercicio 1 2 y 3 la funcion que nos genera una base en $\mathbb{R}^{n}$, pero adicional, definiremos a modo de funcion el operador $U$ y $U^{\dagger}$, las cuales gracias a la definicion del ejercicio como una rotacion, entonces sabemos que $U$ sera una matriz de rotacion en sentido antihorario, y $U^{\dagger}$ una 

In [74]:
def dcroc(i, j):
    if i == j:
        return 1
    else:
        return 0


def baseRn(dim):
    base = []
    for i in range(1, dim + 1):
        base.append([dcroc(j, i) for j in range(1, dim + 1)])
    return np.array(base)


#Rotación sentido antihorario
def U(theta):

    rot_matrix =np.array([ [math.cos(theta*math.pi/180),-math.sin(theta*math.pi/180)],
                           [math.sin(theta*math.pi/180),math.cos(theta*math.pi/180)] ] )
    return rot_matrix

#Rotación sentido horario
def Udag(theta):

    rot_inv_matrix =np.array([ [math.cos(theta*math.pi/180),math.sin(theta*math.pi/180)],
                               [-math.sin(theta*math.pi/180),math.cos(theta*math.pi/180)] ] )
    return rot_inv_matrix

#Producto punto entre dos funciones
def dot(dom,fun1,fun2):
    if dom != None:
        inte = integrate.simpson(fun1*fun2,dom)
        return inte
    else:
        # SI estamos aqui es porque fun1 y fun2 se tratan de vectores
        dot_prod = np.sum(fun1*fun2)
        return dot_prod

Defino una base en $\mathbb{R}^{2}$ como base original

In [75]:
baseR2 = baseRn(2)

u1 = np.array([baseR2[0]]).T
u2 = np.array([baseR2[1]]).T

__Ahora para una matriz A definida como en el ejercicio usando cualquier numero random como representacion de las entradas de a__

In [76]:
a = random()

A = np.array([[a,a],
              [a,-a]])

Por lo que los autovalores de este serán: 

$-(a^{2}-\lambda^{2}) =a^{2} $  --> $\lambda^{2} =2a^{2}$ --> $\lambda^{2} = \pm \sqrt{2}a$


Usamos la matriz de rotación $U$ de tal forma que podamos hallar el $\theta_{0}$ para el cual se cumple que

$D = U^{\dagger}*A*U$


Se puede demostrar que esta transformacion es solo una doble rotación, en el cual $\begin{pmatrix}
a \\a
\end{pmatrix}$ rota hasta $\begin{pmatrix}
\sqrt{2}a \\0
\end{pmatrix}$ y
$\begin{pmatrix}
a \\ -a
\end{pmatrix}$ rota hasta $\begin{pmatrix}
0 \\ -\sqrt{2}a
\end{pmatrix}$, por lo que podemos hallar el angulo que se requiere para la tarea solo aplicando propidedades.
de los vectores.

In [77]:
Au1 = A[:,0:1]
DA = np.array([[np.linalg.norm(Au1)],
               [0]])

print(f"Column_1_(A) = {Au1.T/(np.linalg.norm(Au1))}")
print(f"Rot_Column_1_(A) = {DA.T/(np.linalg.norm(Au1))}")

Column_1_(A) = [[0.70710678 0.70710678]]
Rot_Column_1_(A) = [[1. 0.]]


Usamos estos dos vectores para hallar el angulo entre ellos


In [78]:
theta = (180/math.pi)*math.acos(dot(None,Au1,DA)/(np.linalg.norm(Au1)*np.linalg.norm(DA)))/2

print(f"Angulo de rotación = -{theta}° , -pi/8 rad")

Angulo de rotación = -22.5° , -pi/8 rad


Veamos que en efecto si tenemos la diagonalizacion con este theta

In [79]:
D = np.round(Udag(theta)@A@U(theta)/a,2)

print(f"Udag({theta})*A*U({theta}) = \n\n{D}")

Udag(22.5)*A*U(22.5) = 

[[ 1.41 -0.  ]
 [-0.   -1.41]]


__Sus autovalores normalizados entonces son :__

In [80]:
print(f"lambda1 = {D[0][0]} y lambda2 = {D[1][1]}")

lambda1 = 1.41 y lambda2 = -1.41


Para hallar los auto estados del operador $A$ los hallamos en las columnas de la matriz $U(\theta_{0})$ en este caso, osea la matriz
que se coloca a la izquierda de la matriz diagonal que acabamos de hallar.

In [81]:
print(f"U(22.5) =\n{U(theta)}")

U(22.5) =
[[ 0.92387953 -0.38268343]
 [ 0.38268343  0.92387953]]


Comprobamos que efectivamente si son autovectores.

In [82]:
A1 = A@U(theta)[:,0:1]/(math.sqrt(2)*a)
A2 = A@U(theta)[:,1:2]/(-math.sqrt(2)*a)

print(f"Column_1(U(22.5)) =\n{U(theta)[:,0:1]}\n")
print(f"A*Column_1(U(22.5))/(sqrt(2)*a) = \n{A1}")
print("|||||||||||||||||||||||||||||||||||||||||||||\n")
print(f"Column_2(U(22.5)) =\n{U(theta)[:,1:2]}\n")
print(f"A*Column_2(U(22.5))/(sqrt(2)*a) = \n{A2}")

Column_1(U(22.5)) =
[[0.92387953]
 [0.38268343]]

A*Column_1(U(22.5))/(sqrt(2)*a) = 
[[0.92387953]
 [0.38268343]]
|||||||||||||||||||||||||||||||||||||||||||||

Column_2(U(22.5)) =
[[-0.38268343]
 [ 0.92387953]]

A*Column_2(U(22.5))/(sqrt(2)*a) = 
[[-0.38268343]
 [ 0.92387953]]


__Ya por último solo se tiene que aplicar la rotación para describir los autovectores en la base original $|u_{1}>$ y $|u_{2}>$__

In [83]:
phiA1 = np.round(U(theta)@u1,2)
phiA2 = np.round(U(theta)@u2,2)

print("U(22.5)*|u1> = phiA1")
print("U(22.5)*|u2> = phiA2")


print(f"phiA1 = {phiA1.T} = {phiA1[0][0]}*|u1> + {phiA1[1][0]}*|u2> ")
print(f"phiA2 = {phiA2.T} = {phiA2[0][0]}*|u1> + {phiA2[1][0]}*|u2> ")

U(22.5)*|u1> = phiA1
U(22.5)*|u2> = phiA2
phiA1 = [[0.92 0.38]] = 0.92*|u1> + 0.38*|u2> 
phiA2 = [[-0.38  0.92]] = -0.38*|u1> + 0.92*|u2> 
