# 2 . Desarrollo en bases tridimensionales

Sean los operadores $\hat{A}$ y $\hat{B}$ definidos en el espacio desarrollado por los vectores {$|u1⟩, |u2⟩, |u3⟩$}
como:
$\hat{A} = |u_{1}⟩⟨u_{1}| + |u_{2}⟩⟨u_{2}| + |u_{1}⟩⟨u_{2}| + |u_{2}⟩⟨u_{1}| + |u_{2}⟩⟨u_{3}| + |u_{3}⟩⟨u_{2}| − |u_{1}⟩⟨u_{3}| − |u_{3}⟩⟨u_{1}|$
y

$\hat{B} = 3|u_{1}⟩⟨u_{1}| + 3|u_{2}⟩⟨u_{2}| + 2|u_{3}⟩⟨u_{3}| + |u_{1}⟩⟨u_{2}| + |u_{2}⟩⟨u_{1}|$

Represente matricialmente $|u_{1}⟩, |u_{2}⟩, |u_{3}⟩,⟨u_{1}|,⟨u_{2}| y ⟨u_{3}|$. Calcule las matrices de los operadores
$\hat{A}$ y $\hat{B}$ en la base {$|u_{i}⟩$}${}_{i=1,2,3}$ y compruebe si las matrices conmutan. Encuentre los autovalores
y autovectores de $\hat{A}$ y $\hat{B}$ y calcule la matriz de $\hat{A}$ en la base de autovectores de $\hat{B}$ y viceversa.
Encuentre una base com ́un de autofunciones a partir del resultado anterior. Les recomiendo que usen Mathematica (o Python) o algún otro lenguaje de programación para resolver las operaciones planteadas en este problema.


In [19]:
#Importamos las librerias y funciones que podamos usar sobre la marcha

from sympy.core.random import random
import numpy as np

## Definicion de funciones a usar

In [20]:
def dcroc(i, j):
    if i == j:
        return 1
    else:
        return 0


def baseRn(dim):
    base = []
    for i in range(1, dim + 1):
        base.append([dcroc(j, i) for j in range(1, dim + 1)])
    return np.array(base)


# ADICIONAL UNA FUNCION DE TRANFORMACIÓN DE BASE

def Btransform_old_new(old,new):
    dim = len(old)
    S = []
    for i in range(dim):
        S.append([(old[i].T @ new[j]).sum() for j in range(dim)])
    S =  np.array(S)
    return S

Similar al punto 1, definimos una base tridimensional

In [21]:
dim = 3
base = baseRn(dim)

#Mostramos la representacion matricial de cada KET y cada BRA

u1 = np.array([base[0]]).T
u2 = np.array([base[1]]).T
u3 = np.array([base[2]]).T

print (f"|u1> = \n{u1}\n\n||||||\n\n|u2> = \n{u2}\n\n||||||\n\n|u3> = \n{u3} ")


|u1> = 
[[1]
 [0]
 [0]]

||||||

|u2> = 
[[0]
 [1]
 [0]]

||||||

|u3> = 
[[0]
 [0]
 [1]] 


Y ahora la representacion de los BRAs

In [22]:
print (f"<u1| = {u1.T}\n\n||||||\n\n<u2| = {u2.T}\n\n||||||\n\n<u3| = {u3.T} ")

<u1| = [[1 0 0]]

||||||

<u2| = [[0 1 0]]

||||||

<u3| = [[0 0 1]] 


Similar a como se hizo en el ejercicio del punto 1, calculamos la matriz $A$ y $B$ en la base $u_{i}$

In [23]:
A = u1@u1.T + u2@u2.T + u1@u2.T + u2@u1.T + u2@u3.T + u3@u2.T - u1@u3.T - u3@u1.T
B = 3*u1@u1.T + 3*u2@u2.T + 2*u3@u3.T + u1@u2.T + u2@u1.T

print (f"A = \n {A}\n\n|||||||\n\nB = \n {B}")


A = 
 [[ 1  1 -1]
 [ 1  1  1]
 [-1  1  0]]

|||||||

B = 
 [[3 1 0]
 [1 3 0]
 [0 0 2]]


Veamos de nuevo si las matrices conmutan para un vector cualquiera $Phi$

In [24]:
Phi = random()*u1 -random()*u2 +random()*u3
conmut = A@B - B@A

print(f"[A,B]*phi = {(conmut@Phi).sum()}")

[A,B]*phi = 0.0


Encontremos los autovalores y autovectores de A y B

In [25]:
eigvalsA, eigvecA = np.linalg.eig(A)

eigvalsA = np.round(eigvalsA,3)
eigvecA  = np.round(eigvecA,3)

#Veamos que en efecto se cumple que hayamos los autovectores con sus autovalores

a1 = eigvalsA[0]
a2 = eigvalsA[2]
a3 = eigvalsA[1]

phiA1 = np.array([(eigvecA.T)[0]]).T
phiA2 = np.array([(eigvecA.T)[2]]).T
phiA3 = np.array([(eigvecA.T)[1]]).T

print(f"eigen values of A = {np.array([a1,a2,a3])}")

print(f"eigen vectors of A =\n{np.hstack(   (   phiA1,np.column_stack((phiA2,phiA3))    )   )}\n\n ||||||||||||\n\n")

eigvalsB, eigvecB =  np.linalg.eig(B)

eigvalsB = np.round(eigvalsB,3)
eigvecB  = np.round(eigvecB,3)

## Hacemos lo mismo pero para B

b1 = eigvalsB[1]
b2 = eigvalsB[2]
b3 = eigvalsB[0]

phiB1 = np.array([(eigvecB.T)[1]]).T
phiB2 = np.array([(eigvecB.T)[2]]).T
phiB3 = np.array([(eigvecB.T)[0]]).T

print(f"eigen values of B = {np.array([b1,b2,b3])}")

print(f"eigen vectors of B =\n {np.hstack(   (   phiB1,np.column_stack((phiB2,phiB3))    )   ) }" )

eigen values of A = [-1.414  1.414  2.   ]
eigen vectors of A =
[[ 0.5   -0.5   -0.707]
 [-0.5    0.5   -0.707]
 [ 0.707  0.707  0.   ]]

 ||||||||||||


eigen values of B = [2. 2. 4.]
eigen vectors of B =
 [[-0.707  0.     0.707]
 [ 0.707  0.     0.707]
 [ 0.     1.     0.   ]]


Notese que se colocaron los eigenvalores y en orden de menor a mayor para asegurar de que el cambio de base resulte satisfactorio cuando intentemos hallar una base comun ortonormal de ambos operadores.

**Lo que sigue es entonces representar la matriz de $\hat{A}$ usando la base de autoestados de $\hat{B}$, y viceversa .
Para ello Aplicamos $A^{T} = S^{T}AS$, en donde $S$ se contruye como $<u_{i}|phiB_{j}>$ en donde $u_{i}$ es la base vieja y $phiB_{j}$
la base nueva de autoestados de la diagonalizacion de $B$**



In [26]:
base_old = [u1,u2,u3]
base_newfor_A = [phiB1,phiB2,phiB3]

Su_B = Btransform_old_new(base_old,base_newfor_A)

Aprime = Su_B.T@A@Su_B

"""
    Hacemos lo mismo para B pero usando la base de autoestados de A
"""
base_newfor_B = [phiA1,phiA2,phiA3]

Su_A = Btransform_old_new(base_old,base_newfor_B)

Bprime = Su_A.T@B@Su_A


print (f"A'= \n{np.round(Aprime,2)}\n\n|||||||\n\n")
print (f"B'= \n{np.round(Bprime,2)}")

A'= 
[[0.   1.41 0.  ]
 [1.41 0.   0.  ]
 [0.   0.   2.  ]]

|||||||


B'= 
[[ 2. -0.  0.]
 [-0.  2.  0.]
 [ 0.  0.  4.]]


Como el sub-espacio de los vectores del autovalor degenerado no logran que al cambiar la base, se llegue a una matriz puramente diagonal, se busca llegar a una combinación lineal de estos vectores para que puedan ser autoestados tanto de $\hat{B}$ como de $\hat{A'}$ debido al teorema 4. Tomamos la matriz $A'$ y la diagonalizamos, con esto estaremos encontrando eigenvectores que coinciden con los autoestados de $\hat{B}$

In [27]:
eigvalsAprime, eigvecAprime =  np.linalg.eig(Aprime)

aprime1 = round(eigvalsAprime[1],2)
aprime2 = round(eigvalsAprime[0],2)
aprime3 = round(eigvalsAprime[2],2)

phiAprime1 = np.round(np.array([(eigvecAprime.T)[1]]).T,2)
phiAprime2 = np.round(np.array([(eigvecAprime.T)[0]]).T,2)
phiAprime3 = np.round(np.array([(eigvecAprime.T)[2]]).T,2)

print(f"eigen values of A' = {np.array([aprime1,aprime2,aprime3])}\n")

print(f"eigen vectors of A' = \n{np.hstack(   (   phiAprime1,np.column_stack((phiAprime2,phiAprime3))    )   )}"  )



eigen values of A' = [-1.41  1.41  2.  ]

eigen vectors of A' = 
[[-0.71  0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]


### Logramos a partir de los autovectores de $A'$ llegar a un conjunto de autoestados que coinciden con los autoestados de $\hat{B}$, por lo que $\hat{A'}$ pasa a ser un nuevo operador con autoestados comunes de $\hat{B}$.